# Generated by Django 5.2.8 on 2025-11-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome del modello (es. 'Product')", max_length=100, unique=True)),
                ('table_name', models.CharField(help_text='Nome della tabella nel database', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Model',
                'verbose_name_plural': 'Meta Models',
            },
        ),
        migrations.CreateModel(
            name='MetaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome del campo (es. 'title')", max_length=100)),
                ('field_type', models.CharField(choices=[('char', 'Testo breve'), ('text', 'Testo lungo'), ('integer', 'Numero intero'), ('decimal', 'Numero decimale'), ('boolean', 'Booleano'), ('date', 'Data'), ('datetime', 'Data e ora'), ('foreign_key', 'Relazione'), ('email', 'Email'), ('url', 'URL')], max_length=20)),
                ('verbose_name', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('field_params', models.JSONField(blank=True, default=dict, help_text='\n        Parametri specifici per tipo:\n        - char: max_length\n        - decimal: max_digits, decimal_places\n        - foreign_key: related_model\n    ')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_models.metamodel')),
            ],
            options={
                'verbose_name': 'Meta Field',
                'verbose_name_plural': 'Meta Fields',
                'ordering': ['order', 'id'],
                'unique_together': {('meta_model', 'name')},
            },
        ),
    ]
